# -*- coding: utf-8 -*-
"""EDA_App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M_Nmt5rh2Ca2JcfPBi2N-fmyBmwJ30Td
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings("ignore")

# Page configuration
st.set_page_config(page_title="Complete EDA Application", page_icon="📊", layout="wide")

# Heading and introduction
st.title("📊 Complete EDA Application")
st.markdown("📂Easily upload your dataset and start analyzing it right away!")

# File uploader supporting multiple formats with a unique key
uploaded_file = st.file_uploader(
    "📂 Choose Your Data File",
    type=["csv", "xlsx", "xls", "txt", "json", "xml"],
    key="smart_eda_upload"
)

# Informative message if no file is uploaded
if not uploaded_file:
    st.info("📁Choose a data file to start exploring and visualizing your information")


if uploaded_file:
    df = pd.read_csv(uploaded_file)

    # Data preview
    st.subheader("Data Preview")
    st.dataframe(df.head())

    # Data summary
    st.subheader("Data Summary")
    st.write("Shape:", df.shape)
    st.write("Column Data Types:")
    st.write(df.dtypes)
    st.write("Missing Values:")
    st.write(df.isnull().sum())

if uploaded_file:
    df = pd.read_csv(uploaded_file)

    # Column selection for plotting
    x_col = st.selectbox("Select X-axis column", df.columns)
    y_col = st.selectbox("Select Y-axis column", df.columns)

if uploaded_file:
    col1, col2 = st.columns(2)

    with col1:
        if st.button("📈 Click Here For Line Graph"):
            fig, ax = plt.subplots()
            ax.plot(df[x_col], df[y_col])
            ax.set_xlabel(x_col)
            ax.set_ylabel(y_col)
            ax.set_title("Line Graph")
            st.pyplot(fig)

    with col2:
        if st.button("📊 Click Here For Bar Chart"):
            fig, ax = plt.subplots()
            ax.bar(df[x_col], df[y_col])
            ax.set_xlabel(x_col)
            ax.set_ylabel(y_col)
            ax.set_title("Bar Chart")
            st.pyplot(fig)